adds a space between 'go' and 'to' on line 15 and and delete the void…
LeCoupa/awesome-cheatsheets pull request #278
Opened 2022-04-04 15:21 UTC by MikeGalyen

… modifier on lines 64, 65, and 66

2022-04-07 13:44 UTC, kang8 commented
Looks so good, Why closed it.

2022-04-07 16:37 UTC, MikeGalyen commented
> Looks so good, Why closed it.

I'm new to contributing on GitHub. My mistake.

2022-04-09 02:49 UTC, kang8 requested changes

2022-04-09 02:49 UTC, kang8 commented on languages/java.md
>        i++;
There are also end-of-line spaces.

2022-04-09 02:49 UTC, kang8 commented on languages/java.md
>  ```java
There are also end-of-line spaces.

2022-04-11 09:41 UTC, merged

2022-04-11 09:41 UTC, LeCoupa commented
Thank you to both of you!