Improve: tools/vim.txt, remove irrelevant/opinionated information, add new commands
LeCoupa/awesome-cheatsheets pull request #280
Opened 2022-04-22 16:15 UTC by Gitleptune

Added:
- lots of new keybinds and commands
- commands section
Changed:
-  Reorganised sections so they're in more relevant order for someone new to vim
-  Replaced `CTRL-A` syntax to `<C-a>` to fit the vim syntax
Removed:
- .vimrc section, as it was broken and opinionated, might confuse new users reading it
- plugins section, as it didn't explain how to install them and they are not included in base vim

2022-04-24 02:55 UTC, kang8 requested changes
Awesome PR!

And I have some suggest.

2022-04-24 02:55 UTC, kang8 commented on tools/vim.txt
> +<Esc>                 exit insert mode
pertty format
```suggestion
<Esc>               exit insert mode
```

2022-04-24 02:55 UTC, kang8 commented on tools/vim.txt
> +ca(                 change in and around pair of (, works with { [ " ' too
```suggestion
ci(                 change in pair of (, works with { [ " ' ` < too
ca(                 change in and around pair of (, works with { [ " ' ` < too
```

2022-04-24 02:55 UTC, kang8 commented on tools/vim.txt
> +C                   change to the end of line
```suggestion
C                   change to the end of line (same as c$)
```

2022-04-24 02:55 UTC, kang8 commented on tools/vim.txt
> +da(                 delete in and around pair of (, works with { [ " ' too
```suggestion
di(                 delete in pair of (, works with { [ " ' ` < too
da(                 delete in and around pair of (, works with { [ " ' ` < too
```

2022-04-24 02:55 UTC, kang8 commented on tools/vim.txt
> +ya(                 yank in and around pair of (, works with { [ " ' too
```suggestion
yi(                 yank in pair of (, works with { [ " ' ` < too
ya(                 yank in and around pair of (, works with { [ " ' ` < too
```

2022-04-25 08:07 UTC, Gitleptune commented
Thanks for noticing those! Feel free to squash the commits, I'm not sure how to do so.

2022-04-26 08:31 UTC, kang8 commented
@Gitleptune Actually, you can squash these commit in your local compute, and force push it.

And I don't have permission, you can wait maintainer to review your PR, then merge it.

2023-10-01 14:48 UTC, closed without merging